Sys.setlocale("LC_TIME", "English")
mydata = read.table("household_power_consumption.txt", sep=";", header=TRUE, dec=".", stringsAsFactors = FALSE)
data<-mydata[(mydata$Date=="1/2/2007" | mydata$Date=="2/2/2007"), ]
subData<-paste(data$Date,data$Time, sep=" ")
finalData<-strptime(subData, "%d/%m/%Y %H:%M:%S")
png("plot4.png", width=480,height = 480)
par(mfrow=c(2,2))
plot(finalData, as.numeric(data$Global_active_power), type = "l", xlab = "", ylab="Global Active power")
plot(finalData, as.numeric(data$Voltage), type = "l", xlab = "datetiime", ylab="Voltage")
plot(finalData, as.numeric(data$Sub_metering_1), type = "l", xlab = "", ylab="Energy Submetering")
lines(finalData, as.numeric(data$Sub_metering_2), type = "l", col="red")
lines(finalData, as.numeric(data$Sub_metering_3), type = "l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lty = 1)
plot(finalData, as.numeric(data$Global_reactive_power), type = "l", xlab = "datetime", ylab="Global_reactive_power")
dev.off()
